# docker-compose build --build-arg sshpass= --build-arg vpnuser= --build-arg vpnpass=
# docker-compose up -d
version: '3'
services:
  qbittorrent: 
    build: ./qbittorrent
    image: benwbooth/qbittorrent
    container_name: qbittorrent
    hostname: qbittorrent
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    security_opt:
      - seccomp:unconfined
    #privileged: true
    devices:
      - /dev/net/tun
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /h:/mnt/Downloads
      - /i:/mnt/data
      - /j:/mnt/data2
      - /k:/mnt/external
      - qBittorrent:/home/ben/.local/share/data/qBittorrent
    ports: 
      #- '2222:22'
      - '8080:8080'
    restart: unless-stopped
  jackett:
    image: linuxserver/jackett
    #build: https://github.com/linuxserver/docker-jackett.git
    container_name: jackett
    hostname: jackett
    environment:
      - TZ=US/Pacific
    volumes:
      - jackett:/config
    ports:
      - '9117:9117'
    restart: unless-stopped
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    hostname: radarr
    environment:
      - TZ=US/Pacific
    volumes:
      - radarr:/config
      - /h:/mnt/Downloads
      - /i:/mnt/data
      - /j:/mnt/data2
      - /k:/mnt/external
    ports:
      - '7878:7878'
    restart: unless-stopped
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    hostname: sonarr
    environment:
      - TZ=US/Pacific
    volumes:
      - sonarr:/config
      - /h:/mnt/Downloads
      - /i:/mnt/data
      - /j:/mnt/data2
      - /k:/mnt/external
    ports:
      - '8989:8989'
    restart: unless-stopped
  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    hostname: lidarr
    environment:
      - TZ=US/Pacific
    volumes:
      - lidarr:/config
      - /h:/mnt/Downloads
      - /i:/mnt/data
      - /j:/mnt/data2
      - /k:/mnt/external
    ports:
      - '8686:8686'
    restart: unless-stopped
  hydra2:
    image: linuxserver/hydra2
    container_name: hydra2
    hostname: hydra2
    environment:
      - TZ=US/Pacific
    volumes:
      - hydra2:/config
      - /h:/mnt/Downloads
      - /i:/mnt/data
      - /j:/mnt/data2
      - /k:/mnt/external
    ports:
      - '5076:5076'
    restart: unless-stopped
  cardigann:
    image: linuxserver/cardigann
    container_name: cardigann
    hostname: cardigann
    environment:
      - TZ=US/Pacific
    volumes:
      - cardigann:/config
      - /h:/mnt/Downloads
      - /i:/mnt/data
      - /j:/mnt/data2
      - /k:/mnt/external
    ports:
      - '5060:5060'
    restart: unless-stopped
  nzbget:
    image: linuxserver/nzbget
    container_name: nzbget
    hostname: nzbget
    environment:
      - TZ=US/Pacific
    volumes:
      - nzbget:/config
      - /h:/mnt/Downloads
      - /i:/mnt/data
      - /j:/mnt/data2
      - /k:/mnt/external
    ports:
      - '6789:6789'
    restart: unless-stopped
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    hostname: heimdall
    environment:
      - TZ=US/Pacific
    volumes:
      - heimdall:/config
    ports:
      - '8001:80'
    restart: unless-stopped
  htpcmanager:
    image: linuxserver/htpcmanager
    container_name: htpcmanager
    hostname: htpcmanager
    environment:
      - TZ=US/Pacific
    volumes:
      - htpcmanager:/config
    ports:
      - '8085:8085'
    restart: unless-stopped
  muximux:
    image: linuxserver/muximux
    container_name: muximux
    hostname: muximux
    environment:
      - TZ=US/Pacific
    volumes:
      - muximux:/config
    ports:
      - '8002:80'
    restart: unless-stopped
  organizr:
    image: lsiocommunity/organizr
    container_name: organizr
    hostname: organizr
    environment:
      - TZ=US/Pacific
    volumes:
      - organizr:/config
    ports:
      - '80:80'
    restart: unless-stopped
  portainer:
    image: portainer/portainer
    container_name: portainer
    hostname: portainer
    volumes:
      - portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '9000:9000'
    restart: always
  duplicati:
    image: linuxserver/duplicati
    container_name: duplicati
    hostname: duplicati
    volumes:
      - duplicati:/config
      - /h:/mnt/Downloads
      - /i:/mnt/data
      - /j:/mnt/data2
      - /k:/mnt/external
    environment:
      - TZ=US/Pacific
    ports:
      - '8200:8200'
    restart: unless-stopped
  resilio-sync:
    image: linuxserver/resilio-sync
    container_name: resilio-sync
    hostname: resilio-sync
    volumes:
      - resilio-sync:/config
      - /h:/mnt/Downloads
      - /i:/mnt/data
      - /j:/mnt/data2
      - /k:/mnt/external
    environment:
      - TZ=US/Pacific
    ports:
      - '8888:8888'
      - '55555:55555'
    restart: unless-stopped
  booksonic:
    image: linuxserver/booksonic
    container_name: booksonic
    hostname: booksonic
    volumes:
      - booksonic:/config
      - /h:/mnt/Downloads
      - /i:/mnt/data
      - /j:/mnt/data2
      - /k:/mnt/external
    environment:
      - TZ=US/Pacific
    ports:
      - '4040:4040'
    restart: unless-stopped
  volumerize:
    image: blacklabelops/volumerize
    container_name: volumerize
    hostname: volumerize
    volumes:
      - /k/volumerize-backups:/backup
      - volumerize-cache:/volumerize-cache
      - /var/run/docker.sock:/var/run/docker.sock
      - qBittorrent:/source/qBittorrent:ro
      - jackett:/source/jackett:ro
      - radarr:/source/radarr:ro
      - sonarr:/source/sonarr:ro
      - lidarr:/source/lidarr:ro
      - hydra2:/source/hydra2:ro
      - cardigann:/source/cardigann:ro
      - heimdall:/source/heimdall:ro
      - htpcmanager:/source/htpcmanager:ro
      - muximux:/source/muximux:ro
      - organizr:/source/organizr:ro
      - portainer:/source/portainer:ro
      - duplicati:/source/duplicati:ro
      - resilio-sync:/source/resilio-sync:ro
      - booksonic:/source/booksonic:ro
    environment:
      - TZ=US/Pacific
      - VOLUMERIZE_SOURCE=/source
      - VOLUMERIZE_TARGET=file:///backup
      - VOLUMERIZE_CONTAINERS=qbittorrent jackett radarr sonarr lidarr hydra2 cardigann heimdall htpcmanager muximux organizr portainer duplicati resilio-sync booksonic

volumes:
  qBittorrent:
  jackett:
  radarr:
  sonarr:
  lidarr:
  hydra2:
  cardigann:
  nzbget:
  heimdall:
  htpcmanager:
  muximux:
  organizr:
  portainer:
  duplicati:
  resilio-sync:
  booksonic:
  volumerize-cache: